# Generated by Django 2.0.6 on 2018-11-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_foodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtypes',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
