# Generated by Django 2.0.6 on 2018-11-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_auto_20181126_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtypes',
            old_name='typesport',
            new_name='typesort',
        ),
    ]
