# Generated by Django 2.0.6 on 2018-12-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_auto_20181129_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='jugementstate',
            field=models.IntegerField(default=2),
        ),
    ]
